### PR TITLE
Features

### PR DESCRIPTION
**Pull request by Jerry299**
## Description
Added Home page(landing page) and register component.

## How Has This Been Tested?
No tests yet

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by peterchijioke** [comment]
Success

**Comment by darlingtim** [comment]
@peterchijioke  you should see a  **add your review** button at the top of all pull request that you have been requested to review. Click on it. You can approve or disapprove as you wish.

**Review by darlingtim — DISMISSED** [review]
This is good  although it needs to be modified to suit our needs.
- this branch has conflict with the `develop `  branch.  can you fix those conflict? Or let me see if I can resolve the conflict.

**Review by darlingtim — APPROVED** [review]
I have resolved the conflict in this branch. 
- the landing page needs extra work but it can be merge right now.

**Comment by peterchijioke** [comment]
Extra work that will need to be done will actually depend on the content requested by Jerry. We need subjections base on what should appear on the landing page...

**Comment by peterchijioke** [comment]
For now am working on the certified teacher dashboard of which I also need the possible content of that page... Thank u

**Comment by darlingtim** [comment]
> For now am working on the certified teacher dashboard of which I also need the possible content of that page... Thank u

I have specified some links for the dashboard in the dashboard issues but I will be updating it soon.

**Pull request merged**
